language: elixir
sudo: true
otp_release:
  - 21.0
elixir:
  - 1.7.4
node:
  - 10.14.2
services:
  - postgresql
env:
  global:

cache:
  directories:


install:
  - uname -a
  - sudo apt update
  - sudo apt install yum
  - wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -P /tmp
  - sudo yum install -y /tmp/epel-release-latest-7.noarch.rpm
  - yum update -y
  - yum upgrade -y --enablerepo=epel
  - yum --enablerepo=epel group install -y "Development Tools" #Automake

before_script:
  - elixir -v
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp apps/explorer/config/dev.secret.exs.example apps/explorer/config/dev.secret.exs
  - cp apps/block_scout_web/config/dev.secret.exs.example apps/block_scout_web/config/dev.secret.exs
  - mix do deps.get, local.rebar --force, deps.compile, compile
  - mix ecto.create && mix ecto.migrate
  - cd apps/block_scout_web/assets && npm install; cd -
  - cd apps/explorer && npm install; cd -
  - mix phx.server

script:


