language: elixir
sudo: true
otp_release:
  - 21.0
elixir:
  - 1.7.4
node:
  - 10.14.2
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433

cache:
  directories:


install:
 # - sudo initdb -D PostgreSQL/data
 # - pg_ctl -D PostgreSQL/data/ start
 # - sudo -i -u postgres
 # - sudo -u postgres psql
 # - ALTER USER postgres WITH PASSWORD 'qwerty'
  #- \q
 # - service postgresql status
  #- sudo service postgresql start

  - sudo apt update
  - sudo apt install automake -y
  - sudo apt install libtool -y
  - sudo apt-get install inotify-tools -y
  - gcc -v
  - sudo apt-get install -y libgmp-dev

before_script:
  #- psql -c "CREATE DATABASE testing_db;"
  - psql -c "ALTER USER postgres WITH PASSWORD 'qwerty12345';"
  - psql -c "\du;"
  #- psql -c "\l;"
  - service postgresql status
  - elixir -v
  - cp apps/explorer/config/dev.secret.exs.example apps/explorer/config/dev.secret.exs
  - cp apps/block_scout_web/config/dev.secret.exs.example apps/block_scout_web/config/dev.secret.exs
  - mix local.hex --force
  - mix do deps.get, local.rebar --force, deps.compile, compile
  - psql -c "\du;"
 # - psql -c "\l;"
  - mix ecto.create
  - mix ecto.migrate
  - cd apps/block_scout_web/assets && npm install; cd -
  - cd apps/explorer && npm install; cd -
  - mix phx.server

  - git submodule update --init --recursive --remote
  - cd e2e-blockscout
  - npm i
  - npm run e2e:balance

script:


