language: elixir
sudo: false
otp_release:
  - 21.0
elixir:
  - 1.7.4
node:
  - 10.14.2
services:
  - postgresql
env:
  global:

cache:
  directories:


install:
  - curl -L -o yum-3.4.3.tar.gz http://yum.baseurl.org/download/3.4/yum-3.4.3.tar.gz
    sudo dpkg -i yum-3.4.3.tar.gz
  - yum --enablerepo=epel group install -y "Development Tools"

before_script:
  - elixir -v
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp apps/explorer/config/dev.secret.exs.example apps/explorer/config/dev.secret.exs
  - cp apps/block_scout_web/config/dev.secret.exs.example apps/block_scout_web/config/dev.secret.exs
  - mix do deps.get, local.rebar --force, deps.compile, compile
  - mix ecto.create && mix ecto.migrate
  - cd apps/block_scout_web/assets && npm install; cd -
  - cd apps/explorer && npm install; cd -
  - mix phx.server

script:


