language: elixir
sudo: false
otp_release:
  - 21.0
elixir:
  - 1.7.4
node:
  - 10.14.2
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433

cache:
  directories:


install:
 # - sudo initdb -D PostgreSQL/data
 # - pg_ctl -D PostgreSQL/data/ start
  - sudo -i -u postgres
  - psql
  - /usr/lib/postgresql/10/bin/pg_ctl -D /var/lib/postgresql/10/main -l logfile start
  - sudo apt update
  - sudo apt install automake -y
  - sudo apt install libtool -y
  - sudo apt-get install inotify-tools -y
  - gcc -v
  - sudo apt-get install -y libgmp-dev

before_script:
  - elixir -v
  #- initdb -D CAWA_HOME/PostgreSQL/data
  # - pg_ctl -p PGPORT -D CAWA_HOME/PostgreSQL/data -l logfile start
  #- /usr/lib/postgresql/10/bin/pg_ctl -D /var/lib/postgresql/10/main -l logfile start
  # - /usr/lib/postgresql/10/bin/pg_ctl -D /var/lib/postgresql/10/main -l logfile start
  - cp apps/explorer/config/dev.secret.exs.example apps/explorer/config/dev.secret.exs
  - cp apps/block_scout_web/config/dev.secret.exs.example apps/block_scout_web/config/dev.secret.exs
  - mix local.hex --force
  - mix do deps.get, local.rebar --force, deps.compile, compile
  - mix ecto.create
  - mix ecto.migrate
  - cd apps/block_scout_web/assets && npm install; cd -
  - cd apps/explorer && npm install; cd -
  - mix phx.server

  - git submodule update --init --recursive --remote
  - cd e2e-blockscout
  - npm i
  - npm run e2e:balance

script:


