language: elixir
sudo: false
otp_release:
  - 21.0
elixir:
  - 1.7.4
node:
  - 10.14.2

env:
  global:

cache:
  directories:


install:
  - sudo apt-get install jq
  - pip install awscli --upgrade --user
  - aws --version


script:

